AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus - ${descriptionName}
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  ${resourceName}Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ${handler}
      Runtime: java8
      CodeUri: ${artifact}
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
